site_name: Embedded IoT Linux and OSS Day
site_url: https://boschglobal.github.io/embedded-linux
site_description: Embedded IoT Linux and OSS Day
site_author: Rober Bosch GmbH
copyright: Copyright &copy; 2023 Robert Bosch GmbH

# Plugins
plugins:
  - search
  - macros:
      include_dir: include

nav:
  - Welcome: index.md
  - Speakers: speakers.md
  - Agenda: agenda.md
  - Partners: partners.md
  - Directions: directions.md
  - FAQ: faq.md
  - Contact: contact.md

theme:
  name: material
  logo: images/top97_logo.svg
  custom_dir: overrides
  features:
  - navigation.tabs
  - toc.integrate

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition