site_name: Embedded IoT Linux and OSS Day
site_url: https://boschglobal.github.io/embedded-linux
site_description: Embedded IoT Linux and OSS Day
site_author: Rober Bosch GmbH
copyright: Copyright &copy; 2023 Robert Bosch GmbH
repo_url: https://github.com/boschglobal/embedded-linux
repo_name: bosch/embedded-linux

# Plugins
plugins:
  - search
  - macros:
      verbose: true
      include_dir: include
      include_yaml:
        - keynotes: docs/data/keynotes.yaml
        - talks: docs/data/talks.yaml

nav:
  - Welcome: index.md
  - Agenda: agenda.md
  - Speakers:
    - speakers/index.md
    - Keynotes:
      - keynotes/index.md
      - Siemens: keynotes/siemens.md
      - SUSE: keynotes/suse.md
      - TODO Group: keynotes/todo_group.md
      - Linux Foundation: keynotes/linux_foundation.md
      - Pengutronix: keynotes/pengutronix.md
      - Bosch: keynotes/bosch.md
    - Talks:
      - talks/index.md
      - Mercedes-Benz: talks/mercedes.md
      - SUSE (1): talks/suse_1.md
      - SUSE (2): talks/suse_2.md
      - Bosch TOP97 (1): talks/bosch_top97_1.md
      - Red hat: talks/red_hat.md
      - ETAS: talks/etas.md
      - ADIT: talks/adit.md
      - Bosch TOP 97 (2): talks/bosch_top97_2.md
      - Pengutronix (1): talks/pengutronix_1.md
      - AWS: talks/aws.md
      - Bosch CoC OSS: talks/bosch_coc_oss.md
      - Eclipse: talks/eclipse.md
      - OSADL: talks/osadl.md
      - Bosch TOP97 (3): talks/bosch_top97_3.md
      - Bosch SDV: talks/bosch_sdv.md
      - Codethink: talks/codethink.md
      - Emlix: talks/emlix.md
      - Pengutronix (2): talks/pengutronix_2.md
      - RISC V: talks/risc_v.md

  - Market Place: market_place.md
  - Partners: partners.md
  - Directions: directions.md
  - About:
    - FAQ: faq.md
    - Call for Papers: call_for_papers.md
    - Code of Conduct: code_of_conduct.md
    - Impressum – Legal Disclosure: impressum.md
  - Contact: contact.md

theme:
  name: material
  logo: images/top97_logo.svg
  custom_dir: overrides
  features:
  - navigation.sections
  - navigation.tabs
  - navigation.indexes
  - toc.integrate

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
