site_name: Embedded IoT Linux and OSS Day
site_url: https://boschglobal.github.io/embedded-linux/
site_description: Embedded IoT Linux and OSS Day
site_author: Rober Bosch GmbH
copyright: >
  Copyright &copy; 2023 Robert Bosch GmbH, all rights reserved<br/>
  <a href="/embedded-linux/about/code_of_conduct">Code of Conduct</a>&emsp;
  <a href="/embedded-linux/about/corporate_information">Corporate Information</a>&emsp;
  <a href="/embedded-linux/about/legal_notice">Legal Notice</a>&emsp;
  <a href="/embedded-linux/about/data_protection_notice">Data protection notice (privacy policy)</a>&emsp;
  <a href="#__consent">Privacy settings</a>
repo_url: https://github.com/boschglobal/embedded-linux
repo_name: bosch/embedded-linux

# Plugins
plugins:
  - search
  - macros:
      verbose: true
      include_dir: include
      include_yaml:
        - keynotes: docs/data/keynotes.yaml
        - talks: docs/data/talks.yaml

nav:
  - Welcome: index.md
  - Agenda: agenda.md
  - Speakers:
    - speakers/index.md
    - Keynotes:
      - keynotes/index.md
      - Siemens: keynotes/siemens.md
      - SUSE: keynotes/suse.md
      - TODO Group: keynotes/todo_group.md
      - Linux Foundation: keynotes/linux_foundation.md
      - Pengutronix: keynotes/pengutronix.md
      - Bosch: keynotes/bosch.md
    - Talks:
      - talks/index.md
      - Mercedes-Benz: talks/mercedes.md
      - SUSE (1): talks/suse_1.md
      - SUSE (2): talks/suse_2.md
      - Bosch TOP97 (1): talks/bosch_top97_1.md
      - Bosch IOB: talks/bosch_iob.md
      - Red Hat: talks/red_hat.md
      - ETAS: talks/etas.md
      - ADIT (1): talks/adit_1.md
      - Bosch TOP97 (2): talks/bosch_top97_2.md
      - Eclipse Foundation (1): talks/eclipse_1.md
      - ADIT (2): talks/adit_2.md
      - Bosch TOP97 (3): talks/bosch_top97_3.md
      - Pengutronix (1): talks/pengutronix_1.md
      - AWS: talks/aws.md
      - Bosch CoC OSS, OET: talks/bosch_coc_oss.md
      - Eclipse Foundation (2): talks/eclipse_2.md
      - OSADL: talks/osadl.md
      - Bosch TOP97 (4): talks/bosch_top97_4.md
      - OSADL (2): talks/osadl_2.md
      - Bosch ROS: talks/ros.md
      - Bosch TOP97 (5): talks/bosch_top97_5.md
      - Bosch SDV: talks/bosch_sdv.md
      - Bosch Apertis: talks/bosch_apertis.md
      - Codethink: talks/codethink.md
      - Emlix: talks/emlix.md
      - Collabora: talks/collabora.md
      - Pengutronix (2): talks/pengutronix_2.md
      - RISC-V: talks/risc_v.md
  - Market Place: market_place.md
  - Venue: venue.md
  - About:
    - FAQ: about/faq.md
    - Call for Papers: about/call_for_papers.md
    - Code of Conduct: about/code_of_conduct.md
    - Corporate Information: about/corporate_information.md
    - Legal Notice: about/legal_notice.md
    - Data Protection Notice: about/data_protection_notice.md
  - Contact: contact.md

theme:
  name: material
  logo: images/top97_logo.svg
  custom_dir: overrides
  features:
  - navigation.sections
  - navigation.tabs
  - navigation.indexes
  - toc.integrate

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
